### ISSUE TITLE
mediawiki - max file size (for uploads) needs to be increased to 20M

### ISSUE THREAD

**Issue by tingox** [bitraf/infrastructure#63]
Currently, the new mediawiki reports that the maximum file size is 2M when you try to upload a file. For the old wiki, this was changed to 20M by changing
`post_max_size = 20M`
in php.ini.
So something like this in ansible
```
    - name: increase maximum file size (for uploads) to 20M
      ini_file:
      path: /etc/php/7.0/fpm/php.ini
      section: PHP
      option: post_max_size
      value: 20M
```
Not sure if this should go into ./shared-roles/mediawiki/tasks/main.yml or somewhere else?
Or maybe my approach is wrong?

**Comment by trygvis** [comment]
Sounds like a good approach! You can check the status of `/etc` by running `cd /etc && git status` on the host first.

**Comment by tingox** [comment]
improved code
```
- become: yes
  tags:
    - mediawiki
	- mediawiki-php
	block:
      - name: increase maximum file size (for uploads) to 20M
        ini_file:
        path: /etc/php/7.0/fpm/php.ini
        section: PHP
        option: post_max_size
        value: 20M
```
